os: osx
osx_image: xcode13.1
language: swift
script: xcodebuild clean build test -workspace QuizApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
